# Dot-sourced from install.ps1 - Install-GeneratedScripts.ps1 (v15.2.9 modular split - REVIEWED)
#Requires -Version 5.1

function Invoke-InstallGeneratedScripts {
Invoke-DeployWgSafetyModule -Version $WG_KS_VERSION
OK "wg-safety.ps1 runtime module deployed"

Write-Step "STEP 7 - MONITOR SCRIPT"
# ================================================================
$monitorTunnelSvc  = $TUNNEL_SVC
$monitorTunnelName = $TUNNEL_NAME
$monitorConfig     = $CONFIG
# Use already-resolved values from STEP 6 (no second API call)
$monitorServerIp   = $serverIPs
$monitorPort       = $serverPort
$monitorCustomMode = if ($CUSTOM_MODE) { '$true' } else { '$false' }
$monitorKsVersion  = $WG_KS_VERSION

$monitorContent = @"
# WireGuard Kill Switch - Monitor v$monitorKsVersion (auto-generated by install.ps1)
`$TUNNEL_SVC   = '$monitorTunnelSvc'
`$TUNNEL_NAME  = '$monitorTunnelName'
`$CONFIG       = '$monitorConfig'
`$LOG          = 'C:\WireGuard\killswitch.log'
`$WG_EXE       = 'C:\Program Files\WireGuard\wireguard.exe'
`$REG_KEY      = 'HKLM:\SOFTWARE\WGKillSwitch'
`$CUSTOM_MODE  = $monitorCustomMode
`$script:SERVER_IP = '$monitorServerIp'
`$SERVER_PORT  = '$monitorPort'
`$script:LastServerIP = ''
`$script:ServerIPRefreshTick = 0
`$PID_FILE = 'C:\WireGuard\monitor.pid'
`$SAFETY_MOD = 'C:\WireGuard\wg-safety.ps1'
if (Test-Path `$SAFETY_MOD) { . `$SAFETY_MOD }

function Wait-NamedMutex([System.Threading.Mutex]`$Mutex, [int]`$TimeoutMs) {
    try { return `$Mutex.WaitOne(`$TimeoutMs) }
    catch [System.Threading.AbandonedMutexException] { return `$true }
}

function Write-Emergency([string]`$m) {
    try { Add-Content `$LOG "`$(Get-Date -f 'yyyy-MM-dd HH:mm:ss') | [MON] `$m" -Encoding UTF8 -EA SilentlyContinue } catch {}
}

function Log([string]`$m) {
    `$mutex = `$null
    try {
        `$mutex = New-Object System.Threading.Mutex(`$false, "Global\WGKillSwitchLog")
        if (-not (Wait-NamedMutex `$mutex 3000)) { return }
        Add-Content `$LOG "`$(Get-Date -f 'yyyy-MM-dd HH:mm:ss') | [MON] `$m" -Encoding UTF8 -EA SilentlyContinue
        try {
            `$s = Get-Content `$LOG -Encoding UTF8 -EA Stop
            if (`$s.Count -gt 500) { `$s | Select-Object -Last 250 | Set-Content `$LOG -Encoding UTF8 -Force }
        } catch {}
    } finally { if (`$mutex) { try { `$mutex.ReleaseMutex() } catch {} } }
}

function Test-TunnelAdapterUp {
    for (`$try = 0; `$try -lt 3; `$try++) {
        try {
            foreach (`$a in (Get-NetAdapter -EA SilentlyContinue)) {
                if (`$a.Status -ne 'Up') { continue }
                if (`$a.Name -eq `$TUNNEL_NAME -or `$a.InterfaceDescription -match 'WireGuard') { return `$true }
            }
        } catch {}
        if (`$try -lt 2) { Start-Sleep -Milliseconds 500 }
    }
    return `$false
}

function Test-TunnelRunning {
    `$svcUp = `$false
    try {
        `$svc = Get-Service -Name `$TUNNEL_SVC -ErrorAction SilentlyContinue
        if (`$svc -and `$svc.Status -eq 'Running') { `$svcUp = `$true }
    } catch {}
    if (-not `$svcUp) { `$svcUp = [bool](( & sc.exe query `$TUNNEL_SVC 2>`$null) -match "RUNNING") }
    if (-not `$svcUp) { return `$false }
    return (Test-TunnelAdapterUp)
}

function Test-TcpHost([string]`$HostName, [int]`$Port, [int]`$TimeoutMs = 4000) {
    `$tcp = `$null
    try {
        `$tcp = New-Object System.Net.Sockets.TcpClient
        `$iar = `$tcp.BeginConnect(`$HostName, `$Port, `$null, `$null)
        if (-not `$iar.AsyncWaitHandle.WaitOne(`$TimeoutMs, `$false)) { return `$false }
        try { `$tcp.EndConnect(`$iar) } catch { return `$false }
        return `$true
    } catch { return `$false }
    finally { if (`$tcp) { try { `$tcp.Close() } catch {} } }
}

function Test-Internet {
    `$hits = 0
    foreach (`$h in @('1.1.1.1', '1.0.0.1', '8.8.8.8')) {
        if (Test-TcpHost `$h 443) { `$hits++ }
    }
    return (`$hits -ge 2)
}

function Test-SafeToOpen {
    return (Test-TunnelRunning) -and (Test-Internet)
}

function Enable-DnsLeakProtection {
    netsh advfirewall firewall set rule name="KS-DNS-Block" new enable=yes 2>`$null | Out-Null
    netsh advfirewall firewall set rule name="KS-DNS-Block-TCP" new enable=yes 2>`$null | Out-Null
}

function Disable-DnsLeakProtection {
    netsh advfirewall firewall set rule name="KS-DNS-Block" new enable=no 2>`$null | Out-Null
    netsh advfirewall firewall set rule name="KS-DNS-Block-TCP" new enable=no 2>`$null | Out-Null
}

function Test-InstallInProgress {
    if (Test-Path 'C:\WireGuard\install.inprogress') { return `$true }
    try {
        `$reg = Get-ItemProperty 'HKLM:\SOFTWARE\WGKillSwitch' -EA SilentlyContinue
        return (`$reg.InstallInProgress -eq 1)
    } catch { return `$false }
}

function Test-UnbrickActive {
    try {
        `$reg = Get-ItemProperty 'HKLM:\SOFTWARE\WGKillSwitch' -Name UnbrickUntil -EA SilentlyContinue
        if (`$reg.UnbrickUntil -and (Get-Date) -lt [datetime]`$reg.UnbrickUntil) { return `$true }
    } catch {}
    return `$false
}

function Test-ServerRulePresent {
    try {
        `$out = netsh advfirewall firewall show rule name="KS-WARP-Server-Out" 2>`$null
        if (`$out -notmatch 'Enabled:\s+Yes') { return `$false }
        `$firstIp = (`$script:SERVER_IP -split ',')[0]
        return (`$out -match [regex]::Escape(`$firstIp))
    } catch { return `$false }
}

function Set-ServerRule {
    netsh advfirewall firewall delete rule name="KS-WARP-Server-Out" 2>`$null | Out-Null
    netsh advfirewall firewall add rule name="KS-WARP-Server-Out" dir=out action=allow protocol=UDP remoteip=`$script:SERVER_IP remoteport=`$SERVER_PORT enable=yes | Out-Null
}

function Get-ResolvedServerIP {
    if (`$CUSTOM_MODE) {
        try {
            `$reg = Get-ItemProperty `$REG_KEY -EA SilentlyContinue
            if (`$reg.ServerIP) { return [string]`$reg.ServerIP }
        } catch {}
        return `$script:SERVER_IP
    }
    `$ipList = [System.Collections.Generic.List[string]]::new()
    try {
        `$ep = (Get-Content `$CONFIG -Encoding UTF8 -EA Stop) |
              Where-Object { `$_ -match '^\s*Endpoint\s*=' } | Select-Object -First 1
        if (`$ep -match '=\s*([0-9]+\.[0-9]+\.[0-9]+)\.[0-9]+:') {
            `$prefix = `$Matches[1] + '.0/24'
            if (-not `$ipList.Contains(`$prefix)) { `$ipList.Add(`$prefix) }
        }
    } catch {}
    try {
        `$resp = Invoke-RestMethod 'https://api.cloudflare.com/client/v4/ips' -TimeoutSec 8 -EA Stop
        if (`$resp.success -and `$resp.result.ipv4_cidrs) {
            foreach (`$cidr in `$resp.result.ipv4_cidrs) {
                if (`$cidr -match '^(162\.159\.|104\.16\.)') {
                    if (-not `$ipList.Contains(`$cidr)) { `$ipList.Add(`$cidr) }
                }
            }
        }
    } catch {}
    if (`$ipList.Count -eq 0) { return `$script:SERVER_IP }
    return (`$ipList -join ',')
}

function Enable-Block {
    if (Enable-KillSwitchBlock -ServerIPs `$script:SERVER_IP -ServerPort `$SERVER_PORT -LogPrefix '[MON]') {
        Log "BLOCK active (server `$(`$script:SERVER_IP) allowed)"
    }
}

function Test-BlockRulePresent {
    `$o = netsh advfirewall firewall show rule name="KS-Block-WiFi-Out" 2>`$null | Out-String
    return (`$o -match 'Enabled:\s+Yes')
}

function Disable-Block {
    Disable-KillSwitchBlock
    Log "BLOCK removed - internet open"
}

function Ensure-ServerRule {
    `$script:ServerIPRefreshTick++
    `$rewrite = -not `$script:LastServerIP
    if (`$script:ServerIPRefreshTick -ge 60) {
        `$script:ServerIPRefreshTick = 0
        `$resolved = Get-ResolvedServerIP
        if (`$resolved -ne `$script:LastServerIP) {
            `$script:LastServerIP = `$resolved
            `$script:SERVER_IP = `$resolved
            Log "Server IPs refreshed: `$resolved"
            `$rewrite = `$true
        }
    }
    if (`$rewrite -or -not (Test-ServerRulePresent)) { Set-ServerRule }
}

function Backup-TunnelConfig {
    if (-not (Test-Path `$CONFIG)) { return `$false }
    Copy-Item `$CONFIG "`$CONFIG.bak" -Force
    return `$true
}
function Restore-TunnelConfigIfMissing {
    if (Test-Path `$CONFIG) { return `$true }
    if (Test-Path "`$CONFIG.bak") { Copy-Item "`$CONFIG.bak" `$CONFIG -Force; return `$true }
    `$guardCfg = 'C:\ProgramData\WGKillSwitchGuard\wgcf-profile.conf'
    if (Test-Path `$guardCfg) { Copy-Item `$guardCfg `$CONFIG -Force; return `$true }
    return `$false
}
function Try-ReinstallTunnel {
    `$mux = `$null
    try {
        if (Test-TunnelRunning) { return `$true }
        `$mux = New-Object System.Threading.Mutex(`$false, 'Global\WGTunnelInstallMutex')
        if (-not (Wait-NamedMutex `$mux 90000)) {
            Log "TunnelReinstall: mutex timeout"
            return (Test-TunnelRunning)
        }
        if (Test-TunnelRunning) { return `$true }
        `$svcExists = [bool]((& sc.exe query `$TUNNEL_SVC 2>`$null) -notmatch 'does not exist')
        if (`$svcExists) {
            & sc.exe start `$TUNNEL_SVC 2>`$null | Out-Null
            `$waited = 0
            while (`$waited -lt 30 -and -not (Test-TunnelRunning)) { Start-Sleep 3; `$waited += 3 }
            if (Test-TunnelRunning) { return `$true }
        }
        Restore-TunnelConfigIfMissing | Out-Null
        if (-not (Test-Path `$CONFIG)) {
            Log 'TunnelReinstall: config missing - aborting (no uninstall)'
            return `$false
        }
        Get-Process -Name "wireguard" -EA SilentlyContinue | Stop-Process -Force -EA SilentlyContinue
        `$wgSvcPid = (Get-CimInstance Win32_Service -Filter "Name='`$TUNNEL_SVC'" -EA SilentlyContinue).ProcessId
        if (`$wgSvcPid -and `$wgSvcPid -gt 0) { Stop-Process -Id `$wgSvcPid -Force -EA SilentlyContinue }
        Start-Sleep -Seconds 2
        for (`$attempt = 1; `$attempt -le 2; `$attempt++) {
            Backup-TunnelConfig | Out-Null
            & `$WG_EXE /uninstalltunnelservice `$TUNNEL_NAME 2>`$null | Out-Null
            Start-Sleep -Seconds 4
            Restore-TunnelConfigIfMissing | Out-Null
            if (-not (Test-Path `$CONFIG)) {
                Log "TunnelReinstall: config lost after uninstall - attempt `$attempt"
                continue
            }
            & `$WG_EXE /installtunnelservice `$CONFIG 2>`$null | Out-Null
            & sc.exe start `$TUNNEL_SVC 2>`$null | Out-Null
            `$waited = 0
            while (`$waited -lt 30 -and -not (Test-TunnelRunning)) {
                Start-Sleep -Seconds 3; `$waited += 3
            }
            if (Test-TunnelRunning) { return `$true }
            Log "TunnelReinstall: attempt `$attempt failed (waited `${waited}s)"
        }
        return `$false
    } finally {
        if (`$mux) { try { `$mux.ReleaseMutex() } catch {} }
    }
}

function Invoke-EmergencyUnbrick {
    Log "EMERGENCY UNBRICK: deep gentle unbrick (protection stays installed)"
    Disable-Block
    Disable-DnsLeakProtection
    if (-not (Test-TunnelRunning)) {
        `$n = Restore-DhcpDnsOnPhysicalAdapters
        if (`$n -gt 0) { Log "Fail-open DNS: restored DHCP on `$n adapter(s)" }
    }
    Clear-DnsClientCache -EA SilentlyContinue
    Remove-Item 'C:\WireGuard\install.inprogress' -Force -EA SilentlyContinue
    New-Item -Path `$REG_KEY -Force | Out-Null
    Set-ItemProperty `$REG_KEY 'UnbrickUntil' (Get-Date).AddMinutes(10).ToString('o') -Force
    Remove-ItemProperty `$REG_KEY 'InstallInProgress' -EA SilentlyContinue
    Set-ItemProperty `$REG_KEY 'BootGraceUntil' (Get-Date).AddSeconds(`$script:BOOT_GRACE_SEC).ToString('o') -Force
    return `$true
}

function Remove-OtherMonitorProcs {
    foreach (`$shell in @('powershell', 'pwsh')) {
        Get-Process `$shell -EA SilentlyContinue | ForEach-Object {
            if (`$_.Id -eq `$PID) { return }
            try {
                `$c = (Get-CimInstance Win32_Process -Filter "ProcessId=`$(`$_.Id)" -EA Stop).CommandLine
                if (`$c -match '(?:\\|/)monitor\.ps1(?:\s|"|$)') {
                    Stop-Process -Id `$_.Id -Force -EA SilentlyContinue
                    Log "Duplicate monitor killed (PID: `$(`$_.Id))"
                }
            } catch {}
        }
    }
}

`$mainMux = `$null
try {
    `$mainMux = New-Object System.Threading.Mutex(`$false, 'Global\WGMainMonitorMutex')
    if (-not (Wait-NamedMutex `$mainMux 5000)) { exit 0 }
    if (Test-Path `$PID_FILE) {
        try {
            `$oldPid = [int](Get-Content `$PID_FILE -EA Stop | Select-Object -First 1)
            if (`$oldPid -gt 0 -and `$oldPid -ne `$PID) {
                try {
                    `$oldCmd = (Get-CimInstance Win32_Process -Filter "ProcessId=`$oldPid" -EA Stop).CommandLine
                    if (`$oldCmd -match '(?:\\|/)monitor\.ps1(?:\s|"|$)') { exit 0 }
                } catch {}
                Remove-Item `$PID_FILE -Force -EA SilentlyContinue
            }
        } catch { Remove-Item `$PID_FILE -Force -EA SilentlyContinue }
    }
    Set-Content `$PID_FILE `$PID -Force -EA SilentlyContinue
    Remove-OtherMonitorProcs
} catch [System.UnauthorizedAccessException] {
    Write-Emergency "FATAL: monitor mutex access denied"
    exit 1
} catch {
    Write-Emergency "FATAL: monitor mutex error: `$_"
    exit 1
}

Log "=== Monitor started (v$monitorKsVersion) ==="

`$monitorFatal = `$null
try {

if (Test-InstallInProgress) {
    Disable-Block
    Log "Install in progress - waiting for install.ps1 to finish (internet open)"
    while (Test-InstallInProgress) {
        Start-Sleep -Seconds 5
        Ensure-ServerRule
    }
    Log "Install lock cleared - resuming normal kill switch"
}

try {
    `$graceEnd = Set-BootGraceFromUptime
    if (`$graceEnd) {
        Log "Fresh boot - BootGrace until `$(`$graceEnd.ToString('HH:mm:ss')) (uptime `$(Get-OsUptimeSeconds)s, no block)"
        Disable-KillSwitchBlock
        Start-Sleep -Seconds 15
    }
} catch {}

`$bootWait = 0
while (`$bootWait -lt 90 -and -not (Test-TunnelRunning)) {
    Start-Sleep -Seconds 3; `$bootWait += 3
}

if (Test-SafeToOpen -or Test-BootGrace -or Test-UnbrickActive) {
    `$state = 'open'
    Clear-DnsClientCache -EA SilentlyContinue
    Disable-Block
    if (Test-SafeToOpen) { Log "Startup: healthy (waited `${bootWait}s), internet open" }
    else { Log "Startup: fail-open hold (boot-grace/unbrick), internet open" }
} else {
    `$state = 'open'
    Disable-Block
    if (Test-TunnelRunning) {
        Log "Startup: zombie tunnel suspected (waited `${bootWait}s) - fail-open until debounce"
    } else {
        Log "Startup: tunnel down (waited `${bootWait}s) - fail-open until debounce"
    }
}

`$startupRecovery = `$false
`$wasOpen = (`$state -eq 'open')
`$script:dedupeTick = 0
`$script:tamperTick = 0
`$script:tunnelLostStreak = 0
`$script:zombieStreak = 0

while (`$true) {
    if (-not `$startupRecovery) { Start-Sleep -Seconds 2 }
    `$startupRecovery = `$false
    if (Test-UnbrickActive -or Test-BootGrace -or Test-PostInstallGrace) {
        Disable-Block
        Disable-DnsLeakProtection
        Clear-DnsClientCache -EA SilentlyContinue
        if (`$state -ne 'open') {
            Log "Fail-open hold (unbrick/boot-grace/post-install) - internet open"
            `$state = 'open'; `$wasOpen = `$true
        }
        Start-Sleep -Seconds 30
        continue
    }
    Ensure-ServerRule
    `$script:dedupeTick++
    if (`$script:dedupeTick -ge 15) {
        `$script:dedupeTick = 0
        Remove-OtherMonitorProcs
    }
    `$script:tamperTick++
    if (`$script:tamperTick -ge 30) {
        `$script:tamperTick = 0
        `$at = 'C:\WireGuard\anti-tamper.ps1'
        if (Test-Path `$at) {
            Start-Process -FilePath (Join-Path `$env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe') `
                -ArgumentList @('-NonInteractive','-NoProfile','-WindowStyle','Hidden','-ExecutionPolicy','Bypass','-File',`$at,'-Quick') `
                -WindowStyle Hidden
        }
    }

    if (`$wasOpen -and -not (Test-TunnelRunning)) {
        `$script:tunnelLostStreak++
        if (`$script:tunnelLostStreak -ge 5) {
            if (Test-BlockAllowed) {
                Log "Tunnel lost (confirmed 5x/10s) - block"
                Enable-Block; `$state = 'blocked'; `$wasOpen = `$false
            } else {
                Log "Tunnel lost but block deferred (boot-safe/grace, uptime `$(Get-OsUptimeSeconds)s)"
            }
            `$script:tunnelLostStreak = 0
        }
    } elseif (Test-TunnelRunning) { `$script:tunnelLostStreak = 0 }

    if (Test-SafeToOpen) {
        `$script:zombieStreak = 0
        if (`$state -ne 'open') {
            Clear-DnsClientCache -EA SilentlyContinue
            Disable-Block
            `$state = 'open'
            `$wasOpen = `$true
            Log "Healthy: tunnel + internet OK"
        } else { `$wasOpen = `$true }
        continue
    }

    if (Test-TunnelRunning) {
        `$script:zombieStreak++
        if (`$script:zombieStreak -lt 15) {
            if (`$script:zombieStreak -eq 1) { Log "Zombie tunnel suspected - waiting 15x before block (fail-open)" }
            `$wasOpen = `$false
            Start-Sleep -Seconds 2
            continue
        }
        Log "Zombie tunnel confirmed 15x/30s - block"
    } else {
        `$script:zombieStreak = 0
        Log "Tunnel down - block"
    }
    `$wasOpen = `$false

    if (-not (Test-BlockAllowed)) {
        Log "Unhealthy but block deferred (fail-open hold)"
        continue
    }
    if (`$state -ne 'blocked') {
        Log "WARNING: Unhealthy - activating block after debounce"
    } elseif (-not (Test-BlockRulePresent)) {
        Log "WARNING: Block rules tampered/missing while unhealthy - re-applying"
    }
    Enable-Block
    `$state = 'blocked'
    `$script:zombieStreak = 0

    Log "Starting recovery"
    `$success = `$false
    `$totalAttempts = 0
    while (-not `$success) {
        for (`$i = 1; `$i -le 5; `$i++) {
            if (Test-SafeToOpen) {
                Log "Recovery: healthy before attempt `$i"
                Clear-DnsClientCache -EA SilentlyContinue
                Disable-Block; `$state = 'open'; `$success = `$true; break
            }
            `$totalAttempts++
            Log "Attempt `$i/5 (total: `$totalAttempts)"
            `$up = Try-ReinstallTunnel
            if (`$up) {
                `$waited = 0; `$netOK = `$false
                while (`$waited -lt 30) {
                    if (Test-SafeToOpen) { `$netOK = `$true; break }
                    Start-Sleep -Seconds 5; `$waited += 5
                }
                if (`$netOK) {
                    Log "Attempt `$i - tunnel + internet OK (waited `${waited}s)"
                    Clear-DnsClientCache -EA SilentlyContinue
                    Disable-Block; `$state = 'open'; `$success = `$true; break
                } else {
                    Log "Attempt `$i - tunnel up but no internet after 30s, DNS flush + wait (no re-block)"
                    Clear-DnsClientCache -EA SilentlyContinue
                    Start-Sleep -Seconds 10
                }
            } else {
                Log "Attempt `$i - tunnel did not start"
                Start-Sleep -Seconds 5
            }
        }
        if (-not `$success) {
            Log "CRITICAL: 5 attempts failed (total: `$totalAttempts) - holding 60s then retrying (no re-block)"
            if (`$totalAttempts -ge 5 -and (`$totalAttempts % 5) -eq 0) {
                if (Invoke-EmergencyUnbrick) {
                    `$state = 'open'; `$wasOpen = `$true; `$success = `$true; break
                }
            } elseif (`$totalAttempts -ge 15 -and (`$totalAttempts % 15) -eq 0) {
                Log "STUCK: watchdog will deep-unbrick automatically"
            }
            `$waited = 0
            while (`$waited -lt 60) {
                Start-Sleep -Seconds 3; `$waited += 3
                if (Test-SafeToOpen) {
                    Log "Healthy during 60s hold (tunnel + internet verified)"
                    Clear-DnsClientCache -EA SilentlyContinue
                    Disable-Block; `$state = 'open'; `$wasOpen = `$true; `$success = `$true; break
                }
            }
            if (`$success) { break }
            Log "60s hold done - retrying..."
        }
    }
}

} catch {
    `$monitorFatal = `$_
    Log "FATAL monitor error: `$monitorFatal"
    if (`$script:EnableFailsafe) { Invoke-FailOpenSafeguard -Reason "monitor catch: `$monitorFatal" -LogPrefix '[MON]' }
}
"@
$monitorContent | Set-Content $MONITOR_PS1 -Encoding UTF8 -Force
try {
    $raw = [System.IO.File]::ReadAllText($MONITOR_PS1, [System.Text.Encoding]::UTF8)
    $raw = $raw -replace "(?<!\r)\n", "`r`n"
    [System.IO.File]::WriteAllText($MONITOR_PS1, $raw, [System.Text.Encoding]::UTF8)
} catch {}
attrib -H -S $MONITOR_PS1 2>$null | Out-Null
OK "monitor.ps1 written (server: $monitorServerIp)"

# ================================================================
Write-Step "STEP 8 - REPAIR SCRIPT"
# ================================================================
$repairTunnelSvc  = $TUNNEL_SVC
$repairTunnelName = $TUNNEL_NAME
$repairConfig     = $CONFIG
$repairSvcName    = $WG_SVC_NAME
$repairServerPort = $serverPort

# NOTE: repair.ps1 uses a single-quoted here-string (@' '@) for all static content.
# Variables that must expand at install-time are injected via direct string concatenation.
$repairKsVersion = $WG_KS_VERSION
$repairContent = "# WG Repair Script v$repairKsVersion (auto-generated by install.ps1)`r`n" + @'
$TASK_MONITOR = "WG-KillSwitch"
$MONITOR      = "C:\WireGuard\monitor.ps1"
$LOG          = "C:\WireGuard\killswitch.log"
$WG_EXE       = "C:\Program Files\WireGuard\wireguard.exe"
$LOCK         = "C:\WireGuard\repair.lock"
'@ + "`r`n" + @"
`$TUNNEL_SVC  = '$repairTunnelSvc'
`$TUNNEL_NAME = '$repairTunnelName'
`$CONFIG      = '$repairConfig'
`$WG_SVC_NAME = '$repairSvcName'
`$REG_KEY     = 'HKLM:\SOFTWARE\WGKillSwitch'
`$SERVER_PORT = '$repairServerPort'
"@ + @'

$SAFETY_MOD = 'C:\WireGuard\wg-safety.ps1'
if (Test-Path $SAFETY_MOD) { . $SAFETY_MOD }

$ErrorActionPreference = "SilentlyContinue"

function Wait-NamedMutex([System.Threading.Mutex]$Mutex, [int]$TimeoutMs) {
    try { return $Mutex.WaitOne($TimeoutMs) }
    catch [System.Threading.AbandonedMutexException] { return $true }
}

function Log($m) {
    $mutex = $null
    try {
        $mutex = New-Object System.Threading.Mutex($false, "Global\WGKillSwitchLog")
        if (-not (Wait-NamedMutex $mutex 3000)) { return }
        Add-Content $LOG "$(Get-Date -f 'yyyy-MM-dd HH:mm:ss') | [REPAIR] $m" -Encoding UTF8 -EA SilentlyContinue
        try {
            $s = Get-Content $LOG -Encoding UTF8 -EA Stop
            if ($s.Count -gt 500) { $s | Select-Object -Last 250 | Set-Content $LOG -Encoding UTF8 -Force }
        } catch {}
    } finally { if ($mutex) { try { $mutex.ReleaseMutex() } catch {} } }
}

function Test-TunnelAdapterUp {
    for ($try = 0; $try -lt 3; $try++) {
        try {
            foreach ($a in (Get-NetAdapter -EA SilentlyContinue)) {
                if ($a.Status -ne 'Up') { continue }
                if ($a.Name -eq $TUNNEL_NAME -or $a.InterfaceDescription -match 'WireGuard') { return $true }
            }
        } catch {}
        if ($try -lt 2) { Start-Sleep -Milliseconds 500 }
    }
    return $false
}

function Test-TunnelRunning {
    $svcUp = $false
    try {
        $svc = Get-Service -Name $TUNNEL_SVC -ErrorAction SilentlyContinue
        if ($svc -and $svc.Status -eq 'Running') { $svcUp = $true }
    } catch {}
    if (-not $svcUp) { $svcUp = [bool]((& sc.exe query $TUNNEL_SVC 2>$null) -match "RUNNING") }
    if (-not $svcUp) { return $false }
    return (Test-TunnelAdapterUp)
}

function Test-TcpHost([string]$HostName, [int]$Port, [int]$TimeoutMs = 4000) {
    $tcp = $null
    try {
        $tcp = New-Object System.Net.Sockets.TcpClient
        $iar = $tcp.BeginConnect($HostName, $Port, $null, $null)
        if (-not $iar.AsyncWaitHandle.WaitOne($TimeoutMs, $false)) { return $false }
        try { $tcp.EndConnect($iar) } catch { return $false }
        return $true
    } catch { return $false }
    finally { if ($tcp) { try { $tcp.Close() } catch {} } }
}

function Test-Internet {
    $hits = 0
    foreach ($h in @('1.1.1.1', '1.0.0.1', '8.8.8.8')) {
        if (Test-TcpHost $h 443) { $hits++ }
    }
    return ($hits -ge 2)
}

function Test-SafeToOpen { return (Test-TunnelRunning) -and (Test-Internet) }

function Enable-DnsLeakProtection {
    netsh advfirewall firewall set rule name="KS-DNS-Block" new enable=yes 2>$null | Out-Null
    netsh advfirewall firewall set rule name="KS-DNS-Block-TCP" new enable=yes 2>$null | Out-Null
}

function Disable-DnsLeakProtection {
    netsh advfirewall firewall set rule name="KS-DNS-Block" new enable=no 2>$null | Out-Null
    netsh advfirewall firewall set rule name="KS-DNS-Block-TCP" new enable=no 2>$null | Out-Null
}

function Test-InstallInProgress {
    if (Test-Path 'C:\WireGuard\install.inprogress') { return $true }
    try {
        $reg = Get-ItemProperty $REG_KEY -EA SilentlyContinue
        return ($reg.InstallInProgress -eq 1)
    } catch { return $false }
}

function Test-UnbrickActive {
    try {
        $reg = Get-ItemProperty $REG_KEY -Name UnbrickUntil -EA SilentlyContinue
        if ($reg.UnbrickUntil -and (Get-Date) -lt [datetime]$reg.UnbrickUntil) { return $true }
    } catch {}
    return $false
}

function Test-FwRuleEnabled([string]$name) {
    $o = netsh advfirewall firewall show rule name=$name 2>$null | Out-String
    return ($o -match 'Enabled:\s+Yes')
}

function Test-FwRuleExists([string]$name) {
    $o = netsh advfirewall firewall show rule name=$name 2>$null | Out-String
    return ($o -notmatch 'No rules match')
}

function Get-FwRuleCount([string]$name) {
    $o = netsh advfirewall firewall show rule name=$name 2>$null | Out-String
    if ($o -match 'No rules match') { return 0 }
    return ([regex]::Matches($o, 'Rule Name:')).Count
}

function Test-BlockRulePresent {
    $o = netsh advfirewall firewall show rule name="KS-Block-WiFi-Out" 2>$null | Out-String
    return ($o -match 'Enabled:\s+Yes')
}

function Repair-ConfigIntegrity {
    if (-not (Test-Path $CONFIG)) { return }
    try {
        $raw = [System.IO.File]::ReadAllText($CONFIG)
        if ($raw[0] -eq [char]0xFEFF -or $raw -match '::') {
            Log "Config integrity: fixing BOM/IPv6"
            $out = [System.Collections.Generic.List[string]]::new()
            foreach ($line in ($raw -split "`r?`n")) {
                if ($line -match '^\s*Address\s*=') {
                    $p = ($line -split '=',2)[1].Trim() -split '\s*,\s*' | Where-Object { $_ -and $_ -notmatch ':' }
                    if ($p) { $out.Add("Address = $($p -join ', ')") }
                } elseif ($line -match '^\s*DNS\s*=') {
                    $p = ($line -split '=',2)[1].Trim() -split '\s*,\s*' | Where-Object { $_ -and $_ -notmatch ':' }
                    if ($p) { $out.Add("DNS = $($p -join ', ')") }
                } elseif ($line -match '^\s*AllowedIPs\s*=') {
                    $p = ($line -split '=',2)[1].Trim() -split '\s*,\s*' | Where-Object { $_ -and $_ -notmatch ':' }
                    if ($p) { $out.Add("AllowedIPs = $($p -join ', ')") }
                } elseif ($line.Trim()) { $out.Add($line.TrimEnd()) }
            }
            $enc = New-Object System.Text.UTF8Encoding $false
            [System.IO.File]::WriteAllLines($CONFIG, $out, $enc)
        }
    } catch {}
}

function Repair-EssentialFirewall {
    $serverIp = Get-RepairServerIP
    $alwaysOn = @(
        @{ N='KS-DNS-Allow';     A='netsh advfirewall firewall add rule name="KS-DNS-Allow" dir=out action=allow protocol=UDP remoteip=1.1.1.1,1.0.0.1 remoteport=53 enable=yes' },
        @{ N='KS-WireGuard-EXE'; A='netsh advfirewall firewall add rule name="KS-WireGuard-EXE" dir=out action=allow program="C:\Program Files\WireGuard\wireguard.exe" enable=yes' },
        @{ N='KS-Dnscrypt-EXE'; A='netsh advfirewall firewall add rule name="KS-Dnscrypt-EXE" dir=out action=allow program="C:\WireGuard\dnscrypt-proxy\dnscrypt-proxy.exe" enable=yes' },
        @{ N='KS-WARP-Server-Out'; A="netsh advfirewall firewall add rule name=`"KS-WARP-Server-Out`" dir=out action=allow protocol=UDP remoteip=$serverIp remoteport=$SERVER_PORT enable=yes" }
    )
    $existsOnly = @(
        @{ N='KS-DNS-Block';     A='netsh advfirewall firewall add rule name="KS-DNS-Block" dir=out action=block protocol=UDP remoteport=53 enable=no' },
        @{ N='KS-DNS-Block-TCP'; A='netsh advfirewall firewall add rule name="KS-DNS-Block-TCP" dir=out action=block protocol=TCP remoteport=53 enable=no' }
    )
    foreach ($e in $alwaysOn) {
        $need = (-not (Test-FwRuleExists $e.N)) -or (-not (Test-FwRuleEnabled $e.N)) -or ((Get-FwRuleCount $e.N) -gt 1)
        if ($need) {
            netsh advfirewall firewall delete rule name=$e.N 2>$null | Out-Null
            cmd.exe /c $e.A 2>$null | Out-Null
            Log "Firewall restored: $($e.N)"
        }
    }
    foreach ($e in $existsOnly) {
        if (-not (Test-FwRuleExists $e.N) -or ((Get-FwRuleCount $e.N) -gt 1)) {
            netsh advfirewall firewall delete rule name=$e.N 2>$null | Out-Null
            cmd.exe /c $e.A 2>$null | Out-Null
            Log "Firewall ensured: $($e.N)"
        }
    }
    if (Test-SafeToOpen) { Disable-DnsLeakProtection }
    elseif (Test-BlockRulePresent) { Enable-DnsLeakProtection }
}

function Test-NetworkChanged {
    try {
        $fp = ((Get-NetRoute -DestinationPrefix '0.0.0.0/0' -EA SilentlyContinue | Sort-Object RouteMetric |
                Select-Object InterfaceAlias, NextHop, RouteMetric | Out-String).Trim())
        $reg = Get-ItemProperty $REG_KEY -Name NetworkFingerprint -EA SilentlyContinue
        $prev = [string]$reg.NetworkFingerprint
        if ($prev -and $prev -ne $fp) {
            Set-ItemProperty $REG_KEY NetworkFingerprint $fp -Force -EA SilentlyContinue
            return $true
        }
        Set-ItemProperty $REG_KEY NetworkFingerprint $fp -Force -EA SilentlyContinue
    } catch {}
    return $false
}

function Get-RepairServerIP {
    try {
        $reg = Get-ItemProperty $REG_KEY -EA SilentlyContinue
        if ($reg.ServerIP) { return [string]$reg.ServerIP }
    } catch {}
    return '162.159.192.0/24,104.16.0.0/13'
}

function Disable-Block {
    Disable-KillSwitchBlock
}

function Sync-KillSwitchState {
    if (-not (Test-BlockAllowed)) {
        Disable-Block
        Disable-DnsLeakProtection
        Log "Sync: fail-open hold - internet open"
        return
    }
    if (Test-SafeToOpen) {
        Disable-Block
        Disable-DnsLeakProtection
        Log "Sync: healthy - internet open"
    } else {
        Log "Sync: unhealthy - monitor-only block authority (repair will not block)"
    }
}

function Test-IsMainMonitor([string]$cmd) {
    if ([string]::IsNullOrWhiteSpace($cmd)) { return $false }
    return ($cmd -match '(?:\\|/)monitor\.ps1(?:\s|"|$)')
}

function GetMonitorShellProcs() {
    $found = @()
    foreach ($shell in @('powershell', 'pwsh')) {
        Get-Process $shell -EA SilentlyContinue | ForEach-Object {
            try {
                $c = (Get-CimInstance Win32_Process -Filter "ProcessId=$($_.Id)" -EA Stop).CommandLine
                if (Test-IsMainMonitor $c) { $found += $_ }
            } catch {}
        }
    }
    return $found
}

function Test-MainMonitorActive {
    $pidFile = 'C:\WireGuard\monitor.pid'
    if (Test-Path $pidFile) {
        try {
            $mpid = [int](Get-Content $pidFile -EA Stop | Select-Object -First 1)
            if ($mpid -gt 0) {
                try {
                    $cmd = (Get-CimInstance Win32_Process -Filter "ProcessId=$mpid" -EA Stop).CommandLine
                    if ($cmd -match '(?:\\|/)monitor\.ps1(?:\s|"|$)') { return $true }
                } catch {}
            }
        } catch {}
    }
    return ((GetMonitorShellProcs | Measure-Object).Count -gt 0)
}

function Backup-TunnelConfig {
    if (-not (Test-Path $CONFIG)) { return $false }
    Copy-Item $CONFIG "$CONFIG.bak" -Force
    return $true
}
function Restore-TunnelConfigIfMissing {
    if (Test-Path $CONFIG) { return $true }
    if (Test-Path "$CONFIG.bak") { Copy-Item "$CONFIG.bak" $CONFIG -Force; return $true }
    $guardCfg = 'C:\ProgramData\WGKillSwitchGuard\wgcf-profile.conf'
    if (Test-Path $guardCfg) { Copy-Item $guardCfg $CONFIG -Force; return $true }
    return $false
}
function Try-ReinstallTunnel {
    $mux = $null
    try {
        if (Test-TunnelRunning) { return $true }
        $mux = New-Object System.Threading.Mutex($false, 'Global\WGTunnelInstallMutex')
        if (-not (Wait-NamedMutex $mux 90000)) {
            Log "TunnelReinstall: mutex timeout"
            return (Test-TunnelRunning)
        }
        if (Test-TunnelRunning) { return $true }
        $svcExists = [bool]((& sc.exe query $TUNNEL_SVC 2>$null) -notmatch 'does not exist')
        if ($svcExists) {
            & sc.exe start $TUNNEL_SVC 2>$null | Out-Null
            $waited = 0
            while ($waited -lt 30 -and -not (Test-TunnelRunning)) { Start-Sleep 3; $waited += 3 }
            if (Test-TunnelRunning) { return $true }
        }
        Restore-TunnelConfigIfMissing | Out-Null
        if (-not (Test-Path $CONFIG)) {
            Log 'TunnelReinstall: config missing - aborting (no uninstall)'
            return $false
        }
        Get-Process -Name "wireguard" -EA SilentlyContinue | Stop-Process -Force -EA SilentlyContinue
        $wgSvcPid = (Get-CimInstance Win32_Service -Filter "Name='$TUNNEL_SVC'" -EA SilentlyContinue).ProcessId
        if ($wgSvcPid -and $wgSvcPid -gt 0) { Stop-Process -Id $wgSvcPid -Force -EA SilentlyContinue }
        Start-Sleep -Seconds 2
        for ($attempt = 1; $attempt -le 2; $attempt++) {
            Backup-TunnelConfig | Out-Null
            & $WG_EXE /uninstalltunnelservice $TUNNEL_NAME 2>$null | Out-Null
            Start-Sleep -Seconds 4
            Restore-TunnelConfigIfMissing | Out-Null
            if (-not (Test-Path $CONFIG)) {
                Log "TunnelReinstall: config lost after uninstall - attempt $attempt"
                continue
            }
            & $WG_EXE /installtunnelservice $CONFIG 2>$null | Out-Null
            & sc.exe start $TUNNEL_SVC 2>$null | Out-Null
            $waited = 0
            while ($waited -lt 30 -and -not (Test-TunnelRunning)) {
                Start-Sleep -Seconds 3; $waited += 3
            }
            if (Test-TunnelRunning) { return $true }
            Log "TunnelReinstall: attempt $attempt failed (waited ${waited}s)"
        }
        return $false
    } finally {
        if ($mux) { try { $mux.ReleaseMutex() } catch {} }
    }
}

function Get-PreferredShell {
    $pwshPath = "${env:ProgramFiles}\PowerShell\7\pwsh.exe"
    if (Test-Path $pwshPath) { return $pwshPath }
    $cmd = Get-Command pwsh -EA SilentlyContinue
    if ($cmd) { return $cmd.Source }
    return "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe"
}

function Start-HiddenScript([string]$ScriptPath) {
    $shell = Get-PreferredShell
    $argList = "-NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$ScriptPath`""
    Start-Process -FilePath $shell -ArgumentList $argList -WindowStyle Hidden
}

if (Test-Path $LOCK) {
    $lp = [int](Get-Content $LOCK -EA SilentlyContinue)
    if ($lp -and (Get-Process -Id $lp -EA SilentlyContinue)) { exit 0 }
    Remove-Item $LOCK -Force -EA SilentlyContinue
}
$PID | Set-Content $LOCK -Force -EA SilentlyContinue

try {
    if (Test-Path $LOG) { attrib -H -S $LOG 2>$null | Out-Null }

    if (Test-UnbrickActive -or Test-BootGrace) {
        Disable-Block
        Disable-DnsLeakProtection
        Clear-DnsClientCache -EA SilentlyContinue
        Log "Fail-open hold - repair skipped (no re-block)"
        exit 0
    }

    $atScript = 'C:\WireGuard\anti-tamper.ps1'
    if (Test-Path $atScript) { & $atScript -NoChainRepair }

    $wgPriv = 'C:\WireGuard\privacy-hardening-guard.ps1'
    if (Test-Path $wgPriv) { & $wgPriv }
    else {
        $wgRtc = 'C:\WireGuard\webrtc-leak-guard.ps1'
        if (Test-Path $wgRtc) { & $wgRtc }
    }
    $wgDns = 'C:\WireGuard\dnscrypt-guard.ps1'
    if (Test-Path $wgDns) { & $wgDns }
    $wgDnsLock = 'C:\WireGuard\dns-lockdown-guard.ps1'
    if (Test-Path $wgDnsLock) { & $wgDnsLock }
    $wgNetPriv = 'C:\WireGuard\network-privacy-guard.ps1'
    if (Test-Path $wgNetPriv) { & $wgNetPriv }
    $wgTor = 'C:\WireGuard\tor-hardening-guard.ps1'
    if (Test-Path $wgTor) { & $wgTor }
    $wgTorMon = 'C:\WireGuard\tor-connectivity-monitor.ps1'
    if (Test-Path $wgTorMon) { & $wgTorMon }
    $wgLeak = 'C:\WireGuard\leak-sentinel.ps1'
    if (Test-Path $wgLeak) { & $wgLeak }

    Repair-ConfigIntegrity
    Repair-EssentialFirewall
    if (Test-NetworkChanged) {
        Log "Network change detected (modem/route) - syncing"
        Clear-DnsClientCache -EA SilentlyContinue
        & sc.exe config $TUNNEL_SVC start= delayed-auto 2>$null | Out-Null
    }

    Sync-KillSwitchState

    $policyOK = $true
    foreach ($profile in @("DomainProfile","PrivateProfile","PublicProfile")) {
        if ((netsh advfirewall show $profile 2>$null) -match "BlockOutbound") { $policyOK = $false }
    }
    if (-not $policyOK) {
        netsh advfirewall set allprofiles firewallpolicy blockinbound,allowoutbound | Out-Null
        Log "Firewall policy corrected"
    }

    if ((& sc.exe query MpsSvc 2>$null) -match "STOPPED") {
        & sc.exe start MpsSvc 2>$null | Out-Null; Start-Sleep 3
        netsh advfirewall set allprofiles firewallpolicy blockinbound,allowoutbound | Out-Null
        Log "CRITICAL: Firewall service restarted"
    }

    $task = Get-ScheduledTask -TaskName $TASK_MONITOR -EA SilentlyContinue
    if (-not $task) {
        $b64 = (Get-ItemProperty "HKLM:\SOFTWARE\WGKillSwitch" -Name "TaskXML" -EA SilentlyContinue).TaskXML
        if ($b64) {
            [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($b64)) |
                Register-ScheduledTask -TaskName $TASK_MONITOR -Force | Out-Null
            $taskRun = '\' + $TASK_MONITOR
            schtasks /Run /TN $taskRun 2>$null | Out-Null
            Log "WG-KillSwitch task restored from registry backup"
        } else { Log "CRITICAL: No registry backup found" }
    } elseif ($task.State -eq 'Disabled') {
        Enable-ScheduledTask -TaskName $TASK_MONITOR | Out-Null
        $taskRun = '\' + $TASK_MONITOR
        schtasks /Run /TN $taskRun 2>$null | Out-Null
        Log "WG-KillSwitch task re-enabled"
    }

    if ((& sc.exe query $TUNNEL_SVC 2>$null) -notmatch "RUNNING") {
        if (Test-MainMonitorActive) {
            Log "Tunnel down - monitor active, deferring reinstall (avoid race)"
        } elseif ((Test-Path $WG_EXE) -and (Test-Path $CONFIG)) {
            Log "Tunnel not running - reinstalling (mutex)"
            if (Try-ReinstallTunnel) {
                Log "Tunnel reinstalled OK"
                & sc.exe config $TUNNEL_SVC start= delayed-auto 2>$null | Out-Null
            } else {
                Log "CRITICAL: Tunnel could not be reinstalled"
            }
        }
    } else {
        & sc.exe config $TUNNEL_SVC start= delayed-auto 2>$null | Out-Null
    }

    if ((& sc.exe query $WG_SVC_NAME 2>$null) -notmatch "RUNNING") {
        Log "WGKillSwitchSvc not running - starting"
        & sc.exe start $WG_SVC_NAME 2>$null | Out-Null; Start-Sleep 5
        if ((& sc.exe query $WG_SVC_NAME 2>$null) -match "RUNNING") { Log "WGKillSwitchSvc started" }
        else { Log "CRITICAL: WGKillSwitchSvc could not start" }
    }

    Start-Sleep -Milliseconds 500
    $procs = GetMonitorShellProcs
    if (($procs | Measure-Object).Count -gt 1) {
        $procs | Sort-Object Id | Select-Object -SkipLast 1 | ForEach-Object {
            Stop-Process -Id $_.Id -Force -EA SilentlyContinue
            Log "Duplicate main monitor killed (PID: $($_.Id))"
        }
        Start-Sleep 2
        $procs = GetMonitorShellProcs
    }
    if (-not $procs) {
        Log "Main monitor missing - single direct start"
        Start-HiddenScript $MONITOR
        Log "Monitor start requested"
    }

    Sync-KillSwitchState
} finally {
    Remove-Item $LOCK -Force -EA SilentlyContinue
}
'@
$repairContent | Set-Content $REPAIR_PS1 -Encoding UTF8 -Force
OK "repair.ps1 written"

# ================================================================
Write-Step "STEP 8b - INTERNET WATCHDOG SCRIPT"
# ================================================================
$watchdogKsVersion = $WG_KS_VERSION
$watchdogContent = @"
# Internet Watchdog v$watchdogKsVersion (graduated fail-open - never tears down protection)
`$SAFETY_MOD = 'C:\WireGuard\wg-safety.ps1'
if (Test-Path `$SAFETY_MOD) { . `$SAFETY_MOD }
`$LOG = '$LOG'
`$REG_KEY = 'HKLM:\SOFTWARE\WGKillSwitch'
`$INSTALL_LOCK = '$INSTALL_LOCK'
`$STUCK_FILE = 'C:\WireGuard\watchdog-stuck.count'
`$TUNNEL_SVC = '$TUNNEL_SVC'
`$ErrorActionPreference = 'Continue'

function Log([string]`$m) {
    Add-Content `$LOG "`$(Get-Date -f 'yyyy-MM-dd HH:mm:ss') | [WATCHDOG] `$m" -Encoding UTF8 -EA SilentlyContinue
}
function Test-HoldActive {
    try {
        `$reg = Get-ItemProperty `$REG_KEY -EA SilentlyContinue
        if (`$reg.UnbrickUntil -and (Get-Date) -lt [datetime]`$reg.UnbrickUntil) { return `$true }
        if (`$reg.BootGraceUntil -and (Get-Date) -lt [datetime]`$reg.BootGraceUntil) { return `$true }
    } catch {}
    return `$false
}
function Test-TcpHost([string]`$HostName, [int]`$Port, [int]`$TimeoutMs = 4000) {
    `$tcp = `$null
    try {
        `$tcp = New-Object System.Net.Sockets.TcpClient
        `$iar = `$tcp.BeginConnect(`$HostName, `$Port, `$null, `$null)
        if (-not `$iar.AsyncWaitHandle.WaitOne(`$TimeoutMs, `$false)) { return `$false }
        try { `$tcp.EndConnect(`$iar) } catch { return `$false }
        return `$true
    } catch { return `$false }
    finally { if (`$tcp) { try { `$tcp.Close() } catch {} } }
}
function Test-Internet {
    `$hits = 0
    foreach (`$h in @('1.1.1.1', '1.0.0.1', '8.8.8.8')) {
        if (Test-TcpHost `$h 443) { `$hits++ }
    }
    return (`$hits -ge 2)
}
function Test-TunnelAdapterUp {
    for (`$try = 0; `$try -lt 3; `$try++) {
        try {
            foreach (`$a in (Get-NetAdapter -EA SilentlyContinue)) {
                if (`$a.Status -ne 'Up') { continue }
                if (`$a.InterfaceDescription -match 'WireGuard') { return `$true }
            }
        } catch {}
        if (`$try -lt 2) { Start-Sleep -Milliseconds 500 }
    }
    return `$false
}
function Test-TunnelRunning {
    if (-not ([bool](( & sc.exe query `$TUNNEL_SVC 2>`$null) -match 'RUNNING'))) { return `$false }
    return (Test-TunnelAdapterUp)
}
function Test-BlockRulePresent {
    `$o = netsh advfirewall firewall show rule name="KS-Block-WiFi-Out" 2>`$null | Out-String
    return (`$o -match 'Enabled:\s+Yes')
}
function Invoke-GentleUnbrick {
    Disable-KillSwitchBlock
    if (-not (Test-TunnelRunning)) {
        `$n = Restore-DhcpDnsOnPhysicalAdapters
        if (`$n -gt 0) { Log "Watchdog fail-open DNS: restored DHCP on `$n adapter(s)" }
    }
    Clear-DnsClientCache -EA SilentlyContinue
}
function Invoke-DeepUnbrick {
    Invoke-FailOpenSafeguard -Reason 'watchdog deep unbrick' -LogPrefix '[WATCHDOG]'
    Remove-Item `$INSTALL_LOCK -Force -EA SilentlyContinue
}

if (Test-HoldActive -or (Test-BootSafeWindow)) { exit 0 }

`$tcpOK = Test-Internet
`$tunnel = Test-TunnelRunning
`$healthy = `$tunnel -and `$tcpOK

if (`$healthy) {
    if (Test-BlockRulePresent) {
        Log "Healthy but blocks on - gentle unbrick"
        Invoke-GentleUnbrick
    }
    Set-Content `$STUCK_FILE '0' -Force -EA SilentlyContinue
    exit 0
}

`$count = 0
if (Test-Path `$STUCK_FILE) {
    try { `$count = [int](Get-Content `$STUCK_FILE -EA Stop | Select-Object -First 1) } catch {}
}
`$count++
Set-Content `$STUCK_FILE "`$count" -Force -EA SilentlyContinue

if (`$count -le 2) {
    Log "Unhealthy (tunnel=`$tunnel tcp=`$tcpOK) streak=`$count - gentle unbrick"
    Invoke-GentleUnbrick
    exit 0
}

if (`$count -ge 5) {
    Log "Unhealthy streak=`$count - deep gentle unbrick (tasks/service stay on)"
    Invoke-DeepUnbrick
    Set-Content `$STUCK_FILE '0' -Force -EA SilentlyContinue
} else {
    Log "Unhealthy streak=`$count - gentle unbrick (deep at 5)"
}
"@
Set-Content $WATCHDOG_PS1 $watchdogContent -Encoding UTF8 -Force
OK "internet-watchdog.ps1 written"

# ================================================================
Write-Step "STEP 9 - WMI WRAPPER"
# ================================================================
@'
# WMI Repair Wrapper v12.0 (auto-generated by install.ps1)
$LOG    = 'C:\WireGuard\killswitch.log'
$REPAIR = 'C:\WireGuard\repair.ps1'
$WMI_COOLDOWN = 'C:\WireGuard\wmi-cooldown.txt'
function Wait-NamedMutex([System.Threading.Mutex]$Mutex, [int]$TimeoutMs) {
    try { return $Mutex.WaitOne($TimeoutMs) }
    catch [System.Threading.AbandonedMutexException] { return $true }
}
function Log($m) {
    $mutex = $null
    try {
        $mutex = New-Object System.Threading.Mutex($false, "Global\WGKillSwitchLog")
        if (-not (Wait-NamedMutex $mutex 2000)) { return }
        Add-Content $LOG "$(Get-Date -f 'yyyy-MM-dd HH:mm:ss') | [WMI] $m" -Encoding UTF8 -EA SilentlyContinue
    } finally { if ($mutex) { try { $mutex.ReleaseMutex() } catch {} } }
}
function Test-IsMainMonitor([string]$cmd) {
    if ([string]::IsNullOrWhiteSpace($cmd)) { return $false }
    return ($cmd -match '(?:\\|/)monitor\.ps1(?:\s|"|$)')
}
function GetMonitorShellProcs() {
    $found = @()
    foreach ($shell in @('powershell', 'pwsh')) {
        Get-Process $shell -EA SilentlyContinue | ForEach-Object {
            try {
                $c = (Get-CimInstance Win32_Process -Filter "ProcessId=$($_.Id)" -EA Stop).CommandLine
                if (Test-IsMainMonitor $c) { $found += $_ }
            } catch {}
        }
    }
    return $found
}
function WmiCooldownActive {
    if (-not (Test-Path $WMI_COOLDOWN)) { return $false }
    try {
        $t = [datetime](Get-Content $WMI_COOLDOWN -EA Stop | Select-Object -First 1)
        return ((Get-Date) -lt $t.AddSeconds(45))
    } catch { return $false }
}
if (WmiCooldownActive) { Log "WMI cooldown active - skip"; exit 0 }
Set-Content $WMI_COOLDOWN (Get-Date -Format 'o') -Force -EA SilentlyContinue
Start-Sleep -Seconds 2
$proc = GetMonitorShellProcs
function Get-PreferredShell {
    $pwshPath = "${env:ProgramFiles}\PowerShell\7\pwsh.exe"
    if (Test-Path $pwshPath) { return $pwshPath }
    $cmd = Get-Command pwsh -EA SilentlyContinue
    if ($cmd) { return $cmd.Source }
    return "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe"
}
function Start-HiddenScript([string]$ScriptPath) {
    $shell = Get-PreferredShell
    $argList = "-NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$ScriptPath`""
    Start-Process -FilePath $shell -ArgumentList $argList -WindowStyle Hidden
}
if (-not $proc) {
    Log "Main monitor gone - triggering repair"
    if (Test-Path $REPAIR) { Start-HiddenScript $REPAIR }
} else {
    Log "WMI triggered but main monitor still running - no action"
}
'@ | Set-Content $WMI_WRAPPER -Encoding UTF8 -Force
OK "wmi-repair.ps1 written"

# ================================================================
Write-Step "STEP 10 - SERVICE MONITOR (NSSM wrapper)"
# ================================================================
$svcKsVersion = $WG_KS_VERSION
"# WGKillSwitchSvc wrapper v$svcKsVersion (auto-generated by install.ps1)`r`n" + @'
$LOG       = 'C:\WireGuard\killswitch.log'
$REPAIR    = 'C:\WireGuard\repair.ps1'
$COOLDOWN  = 'C:\WireGuard\repair-cooldown.txt'
$REG_KEY   = 'HKLM:\SOFTWARE\WGKillSwitch'
'@ + "`r`n" + "`$TUNNEL_SVC = '$TUNNEL_SVC'`r`n" + @'
function Wait-NamedMutex([System.Threading.Mutex]$Mutex, [int]$TimeoutMs) {
    try { return $Mutex.WaitOne($TimeoutMs) }
    catch [System.Threading.AbandonedMutexException] { return $true }
}
function Log($m) {
    $mutex = $null
    try {
        $mutex = New-Object System.Threading.Mutex($false, "Global\WGKillSwitchLog")
        if (-not (Wait-NamedMutex $mutex 2000)) { return }
        Add-Content $LOG "$(Get-Date -f 'yyyy-MM-dd HH:mm:ss') | [SVC] $m" -Encoding UTF8 -EA SilentlyContinue
    } finally { if ($mutex) { try { $mutex.ReleaseMutex() } catch {} } }
}
function Test-IsMainMonitor([string]$cmd) {
    if ([string]::IsNullOrWhiteSpace($cmd)) { return $false }
    return ($cmd -match '(?:\\|/)monitor\.ps1(?:\s|"|$)')
}
function GetMonitorShellProcs() {
    $found = @()
    foreach ($shell in @('powershell', 'pwsh')) {
        Get-Process $shell -EA SilentlyContinue | ForEach-Object {
            try {
                $c = (Get-CimInstance Win32_Process -Filter "ProcessId=$($_.Id)" -EA Stop).CommandLine
                if (Test-IsMainMonitor $c) { $found += $_ }
            } catch {}
        }
    }
    return $found
}
function RepairCooldownActive {
    if (-not (Test-Path $COOLDOWN)) { return $false }
    try {
        $t = [datetime](Get-Content $COOLDOWN -EA Stop | Select-Object -First 1)
        return ((Get-Date) -lt $t.AddMinutes(2))
    } catch { return $false }
}
function Test-HoldActive {
    $safety = 'C:\WireGuard\wg-safety.ps1'
    if (Test-Path $safety) {
        . $safety
        if (Test-UnbrickActive -or Test-BootGrace -or (Test-BootSafeWindow)) { return $true }
    }
    try {
        $reg = Get-ItemProperty $REG_KEY -EA SilentlyContinue
        if ($reg.UnbrickUntil -and (Get-Date) -lt [datetime]$reg.UnbrickUntil) { return $true }
        if ($reg.BootGraceUntil -and (Get-Date) -lt [datetime]$reg.BootGraceUntil) { return $true }
    } catch {}
    return $false
}
function Get-PreferredShell {
    $pwshPath = "${env:ProgramFiles}\PowerShell\7\pwsh.exe"
    if (Test-Path $pwshPath) { return $pwshPath }
    $cmd = Get-Command pwsh -EA SilentlyContinue
    if ($cmd) { return $cmd.Source }
    return "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe"
}
function Start-HiddenScript([string]$ScriptPath) {
    $shell = Get-PreferredShell
    $argList = "-NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$ScriptPath`""
    Start-Process -FilePath $shell -ArgumentList $argList -WindowStyle Hidden
}
function TriggerRepair([string]$reason) {
    if (RepairCooldownActive) { return }
    Set-Content $COOLDOWN (Get-Date -Format 'o') -Force -EA SilentlyContinue
    Log $reason
    if (Test-Path $REPAIR) { Start-HiddenScript $REPAIR }
}
'@ + "`r`nLog `"WGKillSwitchSvc started (v$svcKsVersion)`"`r`n" + @'
Start-Sleep -Seconds 15
if (-not (Test-HoldActive)) { TriggerRepair "Initial repair triggered" }
else { Log "Fail-open hold at startup - repair deferred" }
while ($true) {
    if (Test-HoldActive) {
        Start-Sleep -Seconds 60
        continue
    }
    $proc = GetMonitorShellProcs
    $tunnelDown = (( & sc.exe query $TUNNEL_SVC 2>$null) -notmatch 'RUNNING')
    if ($tunnelDown -and $proc) {
        Log "Monitor active - tunnel recovery delegated (no repair spawn)"
        Start-Sleep -Seconds 60
    } elseif ($tunnelDown) {
        TriggerRepair "Tunnel down - urgent repair (immediate)"
        Start-Sleep -Seconds 5
    } elseif (-not $proc) {
        TriggerRepair "Main monitor missing - repair triggered"
        Start-Sleep -Seconds 10
    } else {
        $atPath = 'C:\WireGuard\anti-tamper.ps1'
        if (Test-Path $atPath) {
            Start-Process -FilePath (Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe') `
                -ArgumentList @('-NonInteractive','-NoProfile','-WindowStyle','Hidden','-ExecutionPolicy','Bypass','-File',$atPath,'-Quick') `
                -WindowStyle Hidden
        }
        Start-Sleep -Seconds 60
    }
}
'@ | Set-Content $SERVICE_PS1 -Encoding UTF8 -Force
OK "service-monitor.ps1 written"

# ================================================================
Write-Step "STEP 10b - ANTI-TAMPER GUARD SCRIPT"
# ================================================================
$atRepair = $REPAIR_PS1
$atMonitor = $MONITOR_PS1
$atService = $SERVICE_PS1
$atWmi = $WMI_WRAPPER
$atReboot = $REBOOT_VERIFY_PS1
$atGpo = $GPO_SCRIPT
$atGpoIni = $GPO_INI
$atStartup = $STARTUP_LNK
$atGuard = $GUARD_DIR
$atNssm = $NSSM
$atSvcName = $WG_SVC_NAME
$atTunnelSvc = $TUNNEL_SVC
@"
# WG Anti-Tamper Guard v12.0 (auto-generated by install.ps1)
# Silently restores deleted/disabled protection layers from guard vault + registry.
param([switch]`$Quick, [switch]`$NoChainRepair)
`$ErrorActionPreference = 'SilentlyContinue'
`$REG_KEY = 'HKLM:\SOFTWARE\WGKillSwitch'
`$LOG = 'C:\WireGuard\killswitch.log'
`$GUARD_DIR = '$atGuard'
`$REPAIR = '$atRepair'
`$MONITOR = '$atMonitor'
`$SERVICE_PS1 = '$atService'
`$WMI_WRAPPER = '$atWmi'
`$REBOOT_VERIFY = '$atReboot'
`$GPO_SCRIPT = '$atGpo'
`$GPO_INI = '$atGpoIni'
`$STARTUP_LNK = '$atStartup'
`$NSSM = '$atNssm'
`$WG_SVC_NAME = '$atSvcName'
`$TUNNEL_SVC = '$atTunnelSvc'
`$TASK_MONITOR = 'WG-KillSwitch'
`$TASK_REPAIR = 'WG-RepairTask'
`$TASK_REBOOT_VERIFY = 'WG-RebootVerify'
`$TASK_WATCHDOG = 'WG-InternetWatchdog'
`$WMI_FILTER = 'WGMonitorFilter'
`$WMI_CONSUMER = 'WGMonitorConsumer'
`$EVENT_SRC = 'WGKillSwitch'

function Wait-NamedMutex([System.Threading.Mutex]`$Mutex, [int]`$TimeoutMs) {
    try { return `$Mutex.WaitOne(`$TimeoutMs) }
    catch [System.Threading.AbandonedMutexException] { return `$true }
}
function Log-Tamper([string]`$m) {
    `$mutex = `$null
    try {
        `$mutex = New-Object System.Threading.Mutex(`$false, 'Global\WGKillSwitchLog')
        if (-not (Wait-NamedMutex `$mutex 1500)) { return }
        Add-Content `$LOG "`$(Get-Date -f 'yyyy-MM-dd HH:mm:ss') | [TAMPER] `$m" -Encoding UTF8 -EA SilentlyContinue
    } finally { if (`$mutex) { try { `$mutex.ReleaseMutex() } catch {} } }
}
function Write-TamperEvent([string]`$m) {
    try {
        if (-not [System.Diagnostics.EventLog]::SourceExists(`$EVENT_SRC)) {
            New-EventLog -LogName Application -Source `$EVENT_SRC -EA SilentlyContinue
        }
        Write-EventLog -LogName Application -Source `$EVENT_SRC -EventId 4701 -EntryType Warning -Message `$m -EA SilentlyContinue
    } catch {}
}
function Restore-FileFromGuard([string]`$destPath) {
    if (Test-Path `$destPath) { return `$false }
    `$name = Split-Path `$destPath -Leaf
    `$src = Join-Path `$GUARD_DIR `$name
    if (-not (Test-Path `$src)) { return `$false }
    New-Item -ItemType Directory -Path (Split-Path `$destPath -Parent) -Force -EA SilentlyContinue | Out-Null
    Copy-Item `$src `$destPath -Force
    attrib +S +H `$destPath 2>`$null | Out-Null
    Log-Tamper "Restored file: `$name"
    Write-TamperEvent "WGKillSwitch restored missing file: `$name"
    return `$true
}
function Restore-TaskFromBackup([string]`$TaskName, [string]`$RegProp) {
    `$task = Get-ScheduledTask -TaskName `$TaskName -EA SilentlyContinue
    if (`$task) {
        if (`$task.State -eq 'Disabled') {
            Enable-ScheduledTask -TaskName `$TaskName | Out-Null
            `$tn = '\' + `$TaskName
            schtasks /Run /TN `$tn 2>`$null | Out-Null
            Log-Tamper "Re-enabled task: `$TaskName"
            Write-TamperEvent "WGKillSwitch re-enabled task: `$TaskName"
            return `$true
        }
        return `$false
    }
    `$b64 = (Get-ItemProperty `$REG_KEY -Name `$RegProp -EA SilentlyContinue).`$RegProp
    if (`$b64) {
        [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String(`$b64)) |
            Register-ScheduledTask -TaskName `$TaskName -Force | Out-Null
        Log-Tamper "Restored task from registry: `$TaskName"
        Write-TamperEvent "WGKillSwitch restored task: `$TaskName"
        return `$true
    }
    `$xmlPath = Join-Path `$GUARD_DIR "`$TaskName.xml"
    if (Test-Path `$xmlPath) {
        Register-ScheduledTask -TaskName `$TaskName -Xml (Get-Content `$xmlPath -Raw -Encoding UTF8) -Force | Out-Null
        Log-Tamper "Restored task from guard XML: `$TaskName"
        Write-TamperEvent "WGKillSwitch restored task from guard: `$TaskName"
        return `$true
    }
    return `$false
}
function Ensure-FirewallService {
    `$fixed = `$false
    `$profiles = netsh advfirewall show allprofiles state 2>`$null | Out-String
    if (`$profiles -match 'OFF') {
        netsh advfirewall set allprofiles state on 2>`$null | Out-Null
        netsh advfirewall set allprofiles firewallpolicy blockinbound,allowoutbound 2>`$null | Out-Null
        Log-Tamper 'Firewall profiles forced ON'
        Write-TamperEvent 'WGKillSwitch forced Windows Firewall ON'
        `$fixed = `$true
    }
    if ((& sc.exe query MpsSvc 2>`$null) -match 'STOPPED') {
        & sc.exe start MpsSvc 2>`$null | Out-Null
        Start-Sleep -Seconds 2
        netsh advfirewall set allprofiles firewallpolicy blockinbound,allowoutbound 2>`$null | Out-Null
        Log-Tamper 'MpsSvc restarted'
        Write-TamperEvent 'WGKillSwitch restarted Windows Firewall service'
        `$fixed = `$true
    }
    return `$fixed
}
function Restore-RunKey {
    `$expected = (Get-ItemProperty `$REG_KEY -Name RunKeyValue -EA SilentlyContinue).RunKeyValue
    if (-not `$expected) { `$expected = "powershell.exe -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ``"`$REPAIR``"" }
    `$current = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run' -Name WGKillSwitchGuard -EA SilentlyContinue).WGKillSwitchGuard
    if (`$current -ne `$expected) {
        Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run' WGKillSwitchGuard `$expected -Force
        Log-Tamper 'Run key restored'
        Write-TamperEvent 'WGKillSwitch restored HKLM Run key'
        return `$true
    }
    return `$false
}
function Restore-StartupShortcut {
    if (Test-Path `$STARTUP_LNK) { return `$false }
    New-Item -ItemType Directory -Path (Split-Path `$STARTUP_LNK -Parent) -Force -EA SilentlyContinue | Out-Null
    `$wsh = New-Object -ComObject WScript.Shell
    `$lnk = `$wsh.CreateShortcut(`$STARTUP_LNK)
    `$lnk.TargetPath = 'powershell.exe'
    `$lnk.Arguments = "-NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ``"`$REPAIR``""
    `$lnk.WorkingDirectory = 'C:\WireGuard'
    `$lnk.Save()
    Log-Tamper 'Startup shortcut restored'
    Write-TamperEvent 'WGKillSwitch restored startup shortcut'
    return `$true
}
function Restore-GpoBootScript {
    `$fixed = `$false
    if (-not (Test-Path `$GPO_SCRIPT)) {
        Restore-FileFromGuard `$GPO_SCRIPT | Out-Null
        `$fixed = `$true
    }
    if (Test-Path `$GPO_SCRIPT) {
        `$iniRaw = ''
        if (Test-Path `$GPO_INI) {
            `$iniRaw = Get-Content `$GPO_INI -Raw -Encoding Unicode -EA SilentlyContinue
            if ([string]::IsNullOrWhiteSpace(`$iniRaw)) { `$iniRaw = Get-Content `$GPO_INI -Raw -EA SilentlyContinue }
        }
        if (`$null -eq `$iniRaw) { `$iniRaw = '' }
        if (`$iniRaw -notmatch [regex]::Escape(`$GPO_SCRIPT)) {
            if (`$iniRaw -match '\[Startup\]') {
                `$max = -1; `$in = `$false
                foreach (`$line in (`$iniRaw -split "`r?`n")) {
                    if (`$line -match '^\[Startup\]') { `$in = `$true; continue }
                    if (`$line -match '^\[' -and `$line -notmatch '^\[Startup\]') { `$in = `$false; continue }
                    if (`$in -and `$line -match '^(\d+)CmdLine=') { `$i = [int]`$Matches[1]; if (`$i -gt `$max) { `$max = `$i } }
                }
                `$n = `$max + 1
                `$block = "`${n}CmdLine=powershell.exe`r`n`${n}Parameters=-NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ``"`$GPO_SCRIPT``"`r`n"
                `$iniRaw = `$iniRaw -replace '(\[Startup\]\r?\n)', "`$1`$block"
            } else {
                `$iniRaw += "`r`n[Startup]`r`n0CmdLine=powershell.exe`r`n0Parameters=-NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ``"`$GPO_SCRIPT``"`r`n"
            }
            New-Item -ItemType Directory -Path (Split-Path `$GPO_INI -Parent) -Force -EA SilentlyContinue | Out-Null
            `$iniRaw | Set-Content `$GPO_INI -Encoding Unicode -Force
            Log-Tamper 'GPO scripts.ini entry restored'
            Write-TamperEvent 'WGKillSwitch restored GPO startup registration'
            `$fixed = `$true
        }
    }
    return `$fixed
}
function Test-WmiSubscriptionActive {
    try {
        `$bf = "Filter = ""__EventFilter.Name='`$WMI_FILTER'"""
        `$f = Get-CimInstance -Namespace root\subscription -ClassName __EventFilter -Filter "Name='`$WMI_FILTER'" -EA SilentlyContinue
        if (-not `$f) { return `$false }
        `$c = Get-CimInstance -Namespace root\subscription -ClassName CommandLineEventConsumer -Filter "Name='`$WMI_CONSUMER'" -EA SilentlyContinue
        if (-not `$c) { return `$false }
        `$b = Get-CimInstance -Namespace root\subscription -ClassName __FilterToConsumerBinding -Filter `$bf -EA SilentlyContinue
        return [bool]`$b
    } catch { return `$false }
}
function Restore-WmiSubscription {
    if (Test-WmiSubscriptionActive) { return `$false }
    Get-CimInstance -Namespace root\subscription -ClassName __EventFilter -Filter "Name='`$WMI_FILTER'" -EA SilentlyContinue |
        Remove-CimInstance -EA SilentlyContinue
    Get-CimInstance -Namespace root\subscription -ClassName CommandLineEventConsumer -Filter "Name='`$WMI_CONSUMER'" -EA SilentlyContinue |
        Remove-CimInstance -EA SilentlyContinue
    `$bf = "Filter = ""__EventFilter.Name='`$WMI_FILTER'"""
    Get-CimInstance -Namespace root\subscription -ClassName __FilterToConsumerBinding -Filter `$bf -EA SilentlyContinue |
        Remove-CimInstance -EA SilentlyContinue
    `$wmiQuery = "SELECT * FROM __InstanceDeletionEvent WITHIN 5 WHERE TargetInstance ISA 'Win32_Process' AND (TargetInstance.Name='powershell.exe' OR TargetInstance.Name='pwsh.exe')"
    try {
        `$filter = New-CimInstance -Namespace root\subscription -ClassName __EventFilter -Property @{
            Name=`$WMI_FILTER; EventNamespace='root\cimv2'; QueryLanguage='WQL'; Query=`$wmiQuery
        } -EA Stop
        `$consumer = New-CimInstance -Namespace root\subscription -ClassName CommandLineEventConsumer -Property @{
            Name=`$WMI_CONSUMER
            CommandLineTemplate="powershell.exe -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ``"`$WMI_WRAPPER``""
        } -EA Stop
        if (`$filter -and `$consumer) {
            New-CimInstance -Namespace root\subscription -ClassName __FilterToConsumerBinding -Property @{
                Filter=[Ref]`$filter; Consumer=[Ref]`$consumer
            } -EA Stop | Out-Null
            if (Test-WmiSubscriptionActive) {
                Log-Tamper 'WMI subscription restored'
                Write-TamperEvent 'WGKillSwitch restored WMI permanent subscription'
                return `$true
            }
        }
    } catch {}
    return `$false
}
function Restore-NssmService {
    if (-not (Test-Path `$NSSM)) { return `$false }
    `$q = & sc.exe query `$WG_SVC_NAME 2>`$null | Out-String
    if (`$q -match 'RUNNING') { return `$false }
    if (`$q -notmatch 'SERVICE_NAME') {
        & `$NSSM install `$WG_SVC_NAME powershell.exe 2>`$null | Out-Null
        & `$NSSM set `$WG_SVC_NAME AppParameters "-NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ``"`$SERVICE_PS1``"" 2>`$null | Out-Null
        & `$NSSM set `$WG_SVC_NAME Start SERVICE_DELAYED_AUTO_START 2>`$null | Out-Null
        & `$NSSM set `$WG_SVC_NAME ObjectName LocalSystem 2>`$null | Out-Null
        & `$NSSM set `$WG_SVC_NAME AppExit Default Restart 2>`$null | Out-Null
        & `$NSSM set `$WG_SVC_NAME AppRestartDelay 5000 2>`$null | Out-Null
        Log-Tamper 'NSSM service reinstalled'
        Write-TamperEvent 'WGKillSwitch reinstalled NSSM guard service'
    }
    & sc.exe start `$WG_SVC_NAME 2>`$null | Out-Null
    return `$true
}
function Invoke-AntiTamperGuard {
    if (Test-Path 'C:\WireGuard\install.inprogress') { return }
    try {
        `$reg = Get-ItemProperty `$REG_KEY -EA SilentlyContinue
        if (`$reg.GuardDir) { `$script:GUARD_DIR = [string]`$reg.GuardDir }
    } catch {}
    `$actions = 0
    Ensure-FirewallService | Out-Null
    foreach (`$f in @(`$MONITOR, `$REPAIR, `$SERVICE_PS1, `$WMI_WRAPPER, `$REBOOT_VERIFY, `$GPO_SCRIPT)) {
        if (Restore-FileFromGuard `$f) { `$actions++ }
    }
    if (`$Quick) {
        Restore-TaskFromBackup `$TASK_MONITOR 'TaskXML' | Out-Null
        Restore-TaskFromBackup `$TASK_REPAIR 'TaskXMLRepair' | Out-Null
        return
    }
    if (Restore-TaskFromBackup `$TASK_MONITOR 'TaskXML') { `$actions++ }
    if (Restore-TaskFromBackup `$TASK_REPAIR 'TaskXMLRepair') { `$actions++ }
    if (Restore-TaskFromBackup `$TASK_REBOOT_VERIFY 'TaskXMLRebootVerify') { `$actions++ }
    if (Restore-TaskFromBackup `$TASK_WATCHDOG 'TaskXMLWatchdog') { `$actions++ }
    if (Restore-RunKey) { `$actions++ }
    if (Restore-StartupShortcut) { `$actions++ }
    if (Restore-GpoBootScript) { `$actions++ }
    if (Restore-WmiSubscription) { `$actions++ }
    if (Restore-NssmService) { `$actions++ }
    if (`$actions -gt 0 -and -not `$NoChainRepair -and (Test-Path `$REPAIR)) {
        `$shell = Join-Path `$env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
        Start-Process -FilePath `$shell -ArgumentList @(
            '-NonInteractive','-NoProfile','-WindowStyle','Hidden','-ExecutionPolicy','Bypass','-File',`$REPAIR
        ) -WindowStyle Hidden
    }
}
Invoke-AntiTamperGuard
"@ | Set-Content $ANTI_TAMPER_PS1 -Encoding UTF8 -Force
attrib +S +H $ANTI_TAMPER_PS1 2>$null | Out-Null
OK "anti-tamper.ps1 written"

# ================================================================
Write-Step "STEP 10c - PRIVACY HARDENING GUARD SCRIPT"
# ================================================================
Write-PrivacyHardeningGuardPs1
OK "privacy-hardening-guard.ps1 written"
$privacyGuardVersion = $WG_KS_VERSION
$webrtcForwarder = @'
# WebRTC forwarder (v'@ + $privacyGuardVersion + @')
$ErrorActionPreference = 'SilentlyContinue'
$main = Join-Path (Split-Path $MyInvocation.MyCommand.Path -Parent) 'privacy-hardening-guard.ps1'
if (Test-Path $main) { & $main }
'@
$webrtcForwarder | Set-Content $WEBRTC_GUARD_PS1 -Encoding UTF8 -Force
attrib +S +H $WEBRTC_GUARD_PS1 2>$null | Out-Null
OK "webrtc-leak-guard.ps1 forwarder written"

# ================================================================
Write-Step "STEP 10d - V14 PRIVACY STACK GUARD SCRIPTS"
# ================================================================
if (Get-Command Write-AllV14GuardScripts -EA SilentlyContinue) {
    Write-AllV14GuardScripts
    OK "v14 guard scripts written (dnscrypt/tor/leak-sentinel)"
} else { WARN 'v14 stack missing - guard scripts skipped' }

# ================================================================
Write-Step "STEP 10e - V15 STRONG PRIVACY GUARD SCRIPTS"
# ================================================================
if (Get-Command Write-DnsLockdownGuardPs1 -EA SilentlyContinue) {
    Write-DnsLockdownGuardPs1
    Write-NetworkPrivacyGuardPs1
    if (Get-Command Write-DnscryptGuardPs1V15 -EA SilentlyContinue) { Write-DnscryptGuardPs1V15 }
    if (Get-Command Write-TorHardeningGuardPs1V15 -EA SilentlyContinue) { Write-TorHardeningGuardPs1V15 }
    if (Get-Command Write-LeakSentinelPs1V15 -EA SilentlyContinue) { Write-LeakSentinelPs1V15 }
    OK "v15 guard scripts written (dns-lockdown/network-privacy/leak-sentinel)"
} else { WARN 'v15 stack missing - strong privacy guard scripts skipped' }


}
